import makeType from '../utils/makeType';

export const SEND_ONE_TXT_MSG_TO_QUEUE_OF_ONE_SESSION = makeType('SEND_ONE_TXT_MSG_TO_QUEUE_OF_ONE_SESSION');
export const SEND_ONE_TXT_MSG_TO_QUEUE_OF_ONE_SESSION_RES = makeType('SEND_ONE_TXT_MSG_TO_QUEUE_OF_ONE_SESSION_RES');

export const CONSUME_FROM_QUEUE_OF_ONE_SESSION = makeType('CONSUME_FROM_QUEUE_OF_ONE_SESSION');
export const CONSUME_FROM_QUEUE_OF_ONE_SESSION_RES = makeType('CONSUME_FROM_QUEUE_OF_ONE_SESSION_RES');
