import makeType from '../utils/makeType';

export const PUBLISH_ONE_TXT_MSG_TO_ONE_SESSION = makeType('PUBLISH_ONE_TXT_MSG_TO_ONE_SESSION');
export const PUBLISH_ONE_TXT_MSG_TO_ONE_SESSION_RES = makeType('PUBLISH_ONE_TXT_MSG_TO_ONE_SESSION_RES');

export const SUBSCRIBE_ONE_TOPIC_OF_ONE_SESSION = makeType('SUBSCRIBE_ONE_TOPIC_OF_ONE_SESSION');
export const SUBSCRIBE_ONE_TOPIC_OF_ONE_SESSION_RES = makeType('SUBSCRIBE_ONE_TOPIC_OF_ONE_SESSION_RES');

export const UNSUBSCRIBE_ONE_TOPIC_OF_ONE_SESSION = makeType('UNSUBSCRIBE_ONE_TOPIC_OF_ONE_SESSION');
export const UNSUBSCRIBE_ONE_TOPIC_OF_ONE_SESSION_RES = makeType('UNSUBSCRIBE_ONE_TOPIC_OF_ONE_SESSION_RES');