import makeType from '../utils/makeType';

export const SEND_ONE_TXT_MSG_REQUEST_OF_ONE_SESSION = makeType('SEND_ONE_TXT_MSG_REQUEST_OF_ONE_SESSION');
export const SEND_ONE_TXT_MSG_REQUEST_OF_ONE_SESSION_RES = makeType('SEND_ONE_TXT_MSG_REQUEST_OF_ONE_SESSION_RES');

export const REPLY_ONE_MSG_VIA_TXT_OF_ONE_SESSION = makeType('REPLY_ONE_MSG_VIA_TXT_OF_ONE_SESSION');
export const REPLY_ONE_MSG_VIA_TXT_OF_ONE_SESSION_RES = makeType('REPLY_ONE_MSG_VIA_TXT_OF_ONE_SESSION_RES');